# Generated by Django 3.0.4 on 2020-03-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_regularpizza_siciliannpizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='siciliannpizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
