# Generated by Django 3.0.4 on 2020-03-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200306_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiciliannPizza',
            new_name='SicilianPizza',
        ),
    ]
