# Generated by Django 3.0.4 on 2020-03-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpizza',
            name='toppingWhich',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
