# Generated by Django 3.0.4 on 2020-03-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_regularpizza_toppingwhich'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='extra',
            new_name='extraWhich',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='toppings',
            new_name='toppingsNum',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='toppingWhich',
        ),
        migrations.AddField(
            model_name='cart',
            name='extraNum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cart',
            name='toppingsWhich',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
