# Generated by Django 3.0.4 on 2020-03-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200310_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='subextra',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
    ]
