# Generated by Django 3.0.4 on 2020-03-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200312_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderCart',
        ),
    ]
