# Generated by Django 3.0.4 on 2020-03-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderpaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercart',
            name='dish_price',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='orderpaid',
            name='dish_price',
            field=models.CharField(max_length=64),
        ),
    ]
