# Generated by Django 3.0.4 on 2020-03-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200312_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subextra',
            name='price',
        ),
    ]
