# Generated by Django 3.0.4 on 2020-03-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200315_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaid',
            name='time_stamp',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
